code: .
command: >
  python train.py
environment:
  conda_file: ../environments/train-env.yml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
compute: azureml:cpu-cluster
experiment_name: github-actions-experiment
